FROM oven/bun:1

WORKDIR /usr/src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
COPY ./packages ./packages
COPY ./apps/web ./apps/web
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY . .
RUN bun install
RUN bun run db:migrate
RUN DATABASE_URL=${DATABASE_URL} bun run build
EXPOSE 3001
CMD ["bun", "run", "start:frontend"]